### ISSUE TITLE
Fill "parameters" with "example" from HAR alongside schema

### ISSUE THREAD

**Issue by gvych** [gvych/avantation#2]
At the moment:
```
    /api/estimated: 
      get: 
        parameters: 
          - 
            in: "query"
            name: "amount_from"
            schema: 
              type: "string"
            required: true
```
Expected
```
    /api/estimated: 
      get: 
        parameters: 
          - 
            in: "query"
            name: "amount_from"
            schema: 
              type: "string"
            required: true
            example: "12.12341"
```
